### ISSUE TITLE
Criar DER

### ISSUE THREAD

**Issue by bacciotti** [bacciotti/locadora#56]
Deadline: segunda 10/12.

**Comment by omenegazzi** [comment]
Precisamos mudar algumas coisas do DER, pois o modelo atual não comporta as solicitações da User Stories. Iremos criar uma tabela chamada User(Usuários) e criar mais 2 tabelas de Admin e Dependent, por sua vez elas são ligadas na tabela User, juntamente com a atual tabela que existe que é Client. Todos esse processo de codificação já está pronto no sistema. Basta apenas realizar a alteração no DER, caso queiram eu posso baixar o projeto e fazer a alteração. Falo tranquilamente.

**Comment by bacciotti** [comment]
> Precisamos mudar algumas coisas do DER, pois o modelo atual não comporta as solicitações da User Stories. Iremos criar uma tabela chamada User(Usuários) e criar mais 2 tabelas de Admin e Dependent, por sua vez elas são ligadas na tabela User, juntamente com a atual tabela que existe que é Client. Todos esse processo de codificação já está pronto no sistema. Basta apenas realizar a alteração no DER, caso queiram eu posso baixar o projeto e fazer a alteração. Falo tranquilamente.

Ok, por favor @omenegazzi ou @wemomax atualizem nosso modelo de BD (DER). Enquanto isso eu atualizarei o Relatório Final e outros arquivos. Ah, o @capcin já está preparando nosso Post-Mortem também.

**Comment by wemomax** [comment]
Podemos efetuar todas as alterações no DER entre 11 e 15 de Fevereiro.
