### ISSUE TITLE
Redigir Arquivo 3 - PROCESSO DE DESENVOLVIMENTO

### ISSUE THREAD

**Issue by bacciotti** [bacciotti/locadora#65]

**Comment by omenegazzi** [comment]
Estamos fazendo o máximo possível para documentar.

**Comment by bacciotti** [comment]
Sim, tá ótimo, é isso aí mesmo! Obrigado.

**Comment by bacciotti** [comment]
@bacciotti @omenegazzi @wemomax concluíram o item.
